export default function TermsPage() {
  return (
    <div className="min-h-screen py-24 px-6">
      <div className="max-w-3xl mx-auto prose dark:prose-invert">
        <h1>Terms of Service</h1>
        <p className="text-muted-foreground">Last updated: {new Date().toLocaleDateString()}</p>
        
        <h2>1. Acceptance of Terms</h2>
        <p>
          By accessing and using Northstar (&quot;the Service&quot;), you agree to be bound by these Terms of Service.
        </p>

        <h2>2. Subscription and Billing</h2>
        <p>
          Some aspects of the Service are billed on a subscription basis. You will be billed in advance 
          on a recurring, periodic basis. All fees are non-refundable unless otherwise required by law.
        </p>

        <h2>3. Acceptable Use</h2>
        <p>
          You agree not to use the Service to generate prohibited content, reverse engineer the platform, 
          or attempt to bypass our rate limits and security measures.
        </p>

        <h2>4. Generated Content</h2>
        <p>
          You retain all rights to the input you provide to the Service. Any documents or content 
          generated by the Service based on your input belong to you.
        </p>
        
        <h2>5. Limitation of Liability</h2>
        <p>
          Northstar provides AI-generated drafts. We are not responsible for the business outcomes, 
          technical implementations, or legal standing of the generated specifications. Always review 
          and verify generated documents before use.
        </p>
      </div>
    </div>
  );
}
